let express = require('express');
let router = express.Router();

let UserController = require('../controller/users.controller');

router.post('/signUp', UserController.storeUserDetails);
router.get("/getUserById/:pid", UserController.getUserById);
router.put("/updateUserPassword/:uid",UserController.updateUserPassword);
router.put("/updateUserEmail/:uid",UserController.updateUserEmail);
router.put("/updateUserAddress/:uid",UserController.updateUserAddress);
router.put("/updateUserPhone/:uid",UserController.updateUserPhone);
router.put("/updateUserDOB/:uid", UserController.updateUserDOB);
router.put("/ updateUserFunds/:uid",UserController.updateUserFunds);
router.post("/ticket",UserController.raiseTicket);
router.get("/select", UserController.selectObject);
router.post("/select",UserController.addtoCart);
router.get("/cart/:userId",UserController.viewCart);
router.put("/cart",UserController.updateCart);
router.delete("/cart/:pid",UserController.deleteCart);
//router.get("/orderStatus:/:uid",UserController.getOrderStatus);
router.post('/signUp', UserController.storeUserDetails);
router.get('/getUserById/:pid', UserController.getUserById);
router.put('/lockUser', UserController.lockUser);
router.put('/unlockUsers/', UserController.unlockUser);
router.post('/ticket', UserController.raiseTicket);
router.get('/select', UserController.selectObject);
router.post('/select', UserController.addtoCart);
router.post("/cart",UserController.PurchaseInfo);
router.post("/changeFunds",UserController.changeUserFund);
module.exports = router;